### ISSUE TITLE
关于使用python开发add-on软件包的指南

### ISSUE THREAD

**Issue by MSK-19090** [JakaCobot/jaka_addon_kit#1]
在贵司当前的帮助文档里只有使用node-red开发add-on的指导文档，能否请贵司提供使用python时的指导文档。如自定义指令的开发，关于接口的使用等。谢谢！

**Comment by brycenhe** [comment]
Hi，在使用 Python 开发自定义指令仅在 1.7.0 版本的控制器使用，目前已经不再推荐使用和维护了。但是 Python 依然可以作为后端服务类型的 AddOn 被使用。可以通过在 ini 文件中指定语言为 Python 和 指定入口文件即可。 
![image](https://github.com/JakaCobot/jaka_addon_kit/assets/89619125/c8893c4b-bb6b-4f40-b391-e1f120078c56)
